### PR TITLE
Add LICENSE-* into vte_generate-state_changes

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Raits <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Review by chrisduerr — COMMENTED** [review]
Does it have any specific reason why you are adding these license files? The license for cargo is already part of the Cargo.toml, so the license files in the root should be sufficient.

**Comment by ignatenkobrain** [comment]
Same reason I did it last time :)

When packaging crates, we take an archive from crates.io. All crates are separate units, so license should be present in all of them.

**Comment by kchibisov** [comment]
It seems like Apache license is missing the actual copyright part. Also, since you're adding `MIT` here, and it wasn't there before it should be updated as well.

@chrisduerr what do you think?

**Comment by chrisduerr** [comment]
> @chrisduerr what do you think?

I think the licenses should just be symlinks to the root directory. That's true for utf8parse too.

I also think that a crates.io packaging infrastructure should be able to look at the `license` field of the Cargo.toml, but that's a different story.

**Review by ghcom275 — APPROVED** [review]

**Comment by chrisduerr** [comment]
Closing due to inactivity. If someone is interested in picking this back up, please open a new PR.

**Pull request closed without merging**
